name: sanchu4b
description: 天運三柱推命ver.4.0.36

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 4.0.36+36

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    # 日本語化するために0.18.0 を　0.17.0 にする必要あり(2022.12.17)
  intl: ^0.17.0



  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  shared_preferences: ^2.0.16
  flutter_lints: ^2.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter

#アプリアイコンを作成するためのコード・ここから（2022.12.25)
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: 'images/main/icon_uranai4b.png'
#アプリアイコンを作成するためのコード・ここまで

#スプラッシュ画面を作成する時下記のコードを使う(2022.12.26)
  flutter_native_splash: ^2.2.16

flutter_native_splash:
  image: images/main/icon_uranai4b.png
  color: "000000"
  android: true
  ios: true
#スプラッシュ画面を作成するためのコードここまで




# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - images/main/gogyou1.png
    - images/main/taxi.png
    - images/nikkan/甲_大樹.jpg
    - images/nikkan/甲_木陰.jpg
    - images/nikkan/丁_キャンドル.jpg
    - images/nikkan/丁_燃える炎.jpg
    - images/nikkan/丙_太陽.jpg
    - images/nikkan/丙_朝日.jpg
    - images/nikkan/乙_からみつく.jpg
    - images/nikkan/乙_イラスト１.jpg
    - images/nikkan/壬_支流.jpg
    - images/nikkan/壬_海.jpg
    - images/nikkan/己_畑土.jpg
    - images/nikkan/己_陶芸.jpg
    - images/nikkan/庚_剣.jpg
    - images/nikkan/庚_鍛える.jpg
    - images/nikkan/戊_岩山.jpg
    - images/nikkan/戊_石垣.jpg
    - images/nikkan/癸_潤う.jpg
    - images/nikkan/癸_雲雨.jpg
    - images/nikkan/辛_宝石.jpg
    - images/nikkan/辛_王冠.jpg
    - images/tentitokugou/anehaturu.jpg
    - images/tentitokugou/anehaturu1.jpg
    - images/tentitokugou/anehaturu2.jpg
    - images/tuuhenbosi/00.jpg
    - images/tuuhenbosi/01.jpg
    - images/tuuhenbosi/02.jpg
    - images/tuuhenbosi/03.jpg
    - images/tuuhenbosi/04.jpg
    - images/tuuhenbosi/05.jpg
    - images/tuuhenbosi/06.jpg
    - images/tuuhenbosi/07.jpg
    - images/tuuhenbosi/08.jpg
    - images/tuuhenbosi/09.jpg
    - images/tuuhenbosi/10.jpg
    - images/tuuhenbosi/11.jpg
    - images/tuuhenbosi/12.jpg
    - images/tuuhenbosi/13.jpg
    - images/tuuhenbosi/14.jpg
    - images/tuuhenbosi/15.jpg
    - images/tuuhenbosi/16.jpg
    - images/tuuhenbosi/17.jpg
    - images/tuuhenbosi/18.jpg
    - images/tuuhenbosi/19.jpg
    - images/tuuhenbosi/20.jpg
    - images/tuuhenbosi/21.jpg
    - images/tuuhenbosi/22.jpg
    - images/tuuhenbosi/23.jpg
    - images/tuuhenbosi/24.jpg
    - images/tuuhenbosi/25.jpg
    - images/tuuhenbosi/26.jpg
    - images/tuuhenbosi/27.jpg
    - images/tuuhenbosi/28.jpg
    - images/tuuhenbosi/29.jpg
    - images/tuuhenbosi/30.jpg
    - images/tuuhenbosi/31.jpg
    - images/tuuhenbosi/32.jpg
    - images/tuuhenbosi/33.jpg
    - images/tuuhenbosi/34.jpg
    - images/tuuhenbosi/35.jpg
    - images/tuuhenbosi/36.jpg
    - images/tuuhenbosi/37.jpg
    - images/tuuhenbosi/38.jpg
    - images/tuuhenbosi/39.jpg
    - images/tuuhenbosi/40.jpg
    - images/tuuhenbosi/41.jpg
    - images/tuuhenbosi/42.jpg
    - images/tuuhenbosi/43.jpg
    - images/tuuhenbosi/44.jpg
    - images/tuuhenbosi/45.jpg
    - images/tuuhenbosi/46.jpg
    - images/tuuhenbosi/47.jpg
    - images/tuuhenbosi/48.jpg
    - images/tuuhenbosi/49.jpg
    - images/sigou/s00.jpg
    - images/sigou/s01.jpg
    - images/sigou/s02.jpg
    - images/sigou/s03.jpg
    - images/sigou/s04.jpg
    - images/sigou/s05.jpg
    - images/sigou/s06.jpg
    - images/sigou/s07.jpg
    - images/sigou/s08.jpg
    - images/sigou/s09.jpg
    - images/sigou/s0a.jpg
    - images/sigou/s0b.jpg
    - images/sigou/s00.jpg
    - images/sigou/s01.jpg
    - images/sigou/s02.jpg
    - images/sigou/s03.jpg
    - images/sigou/s04.jpg
    - images/sigou/s05.jpg
    - images/sigou/s06.jpg
    - images/sigou/s07.jpg
    - images/sigou/s08.jpg
    - images/sigou/s09.jpg
    - images/sigou/s0a.jpg
    - images/sigou/s0b.jpg
    - images/sigou/s10.jpg
    - images/sigou/s11.jpg
    - images/sigou/s12.jpg
    - images/sigou/s13.jpg
    - images/sigou/s14.jpg
    - images/sigou/s15.jpg
    - images/sigou/s16.jpg
    - images/sigou/s17.jpg
    - images/sigou/s18.jpg
    - images/sigou/s19.jpg
    - images/sigou/s1a.jpg
    - images/sigou/s1b.jpg
    - images/sigou/s20.jpg
    - images/sigou/s21.jpg
    - images/sigou/s22.jpg
    - images/sigou/s23.jpg
    - images/sigou/s24.jpg
    - images/sigou/s25.jpg
    - images/sigou/s26.jpg
    - images/sigou/s27.jpg
    - images/sigou/s28.jpg
    - images/sigou/s29.jpg
    - images/sigou/s2a.jpg
    - images/sigou/s2b.jpg
    - images/sigou/s30.jpg
    - images/sigou/s31.jpg
    - images/sigou/s32.jpg
    - images/sigou/s33.jpg
    - images/sigou/s34.jpg
    - images/sigou/s35.jpg
    - images/sigou/s36.jpg
    - images/sigou/s37.jpg
    - images/sigou/s38.jpg
    - images/sigou/s39.jpg
    - images/sigou/s3a.jpg
    - images/sigou/s3b.jpg
    - images/sigou/s40.jpg
    - images/sigou/s41.jpg
    - images/sigou/s42.jpg
    - images/sigou/s43.jpg
    - images/sigou/s44.jpg
    - images/sigou/s45.jpg
    - images/sigou/s46.jpg
    - images/sigou/s47.jpg
    - images/sigou/s48.jpg
    - images/sigou/s49.jpg
    - images/sigou/s4a.jpg
    - images/sigou/s4b.jpg
    - images/sigou/s50.jpg
    - images/sigou/s51.jpg
    - images/sigou/s52.jpg
    - images/sigou/s53.jpg
    - images/sigou/s54.jpg
    - images/sigou/s55.jpg
    - images/sigou/s56.jpg
    - images/sigou/s57.jpg
    - images/sigou/s58.jpg
    - images/sigou/s59.jpg
    - images/sigou/s5a.jpg
    - images/sigou/s5b.jpg
    - images/sigou/s60.jpg
    - images/sigou/s61.jpg
    - images/sigou/s62.jpg
    - images/sigou/s63.jpg
    - images/sigou/s64.jpg
    - images/sigou/s65.jpg
    - images/sigou/s66.jpg
    - images/sigou/s67.jpg
    - images/sigou/s68.jpg
    - images/sigou/s69.jpg
    - images/sigou/s6a.jpg
    - images/sigou/s6b.jpg
    - images/sigou/s70.jpg
    - images/sigou/s71.jpg
    - images/sigou/s72.jpg
    - images/sigou/s73.jpg
    - images/sigou/s74.jpg
    - images/sigou/s75.jpg
    - images/sigou/s76.jpg
    - images/sigou/s77.jpg
    - images/sigou/s78.jpg
    - images/sigou/s79.jpg
    - images/sigou/s7a.jpg
    - images/sigou/s7b.jpg
    - images/sigou/s80.jpg
    - images/sigou/s81.jpg
    - images/sigou/s82.jpg
    - images/sigou/s83.jpg
    - images/sigou/s84.jpg
    - images/sigou/s85.jpg
    - images/sigou/s86.jpg
    - images/sigou/s87.jpg
    - images/sigou/s88.jpg
    - images/sigou/s89.jpg
    - images/sigou/s8a.jpg
    - images/sigou/s8b.jpg
    - images/sigou/s90.jpg
    - images/sigou/s91.jpg
    - images/sigou/s92.jpg
    - images/sigou/s93.jpg
    - images/sigou/s94.jpg
    - images/sigou/s95.jpg
    - images/sigou/s96.jpg
    - images/sigou/s97.jpg
    - images/sigou/s98.jpg
    - images/sigou/s99.jpg
    - images/sigou/s9a.jpg
    - images/sigou/s9b.jpg
    - images/sigou/sa0.jpg
    - images/sigou/sa1.jpg
    - images/sigou/sa2.jpg
    - images/sigou/sa3.jpg
    - images/sigou/sa4.jpg
    - images/sigou/sa5.jpg
    - images/sigou/sa6.jpg
    - images/sigou/sa7.jpg
    - images/sigou/sa8.jpg
    - images/sigou/sa9.jpg
    - images/sigou/saa.jpg
    - images/sigou/sab.jpg
    - images/sigou/sb0.jpg
    - images/sigou/sb1.jpg
    - images/sigou/sb2.jpg
    - images/sigou/sb3.jpg
    - images/sigou/sb4.jpg
    - images/sigou/sb5.jpg
    - images/sigou/sb6.jpg
    - images/sigou/sb7.jpg
    - images/sigou/sb8.jpg
    - images/sigou/sb9.jpg
    - images/sigou/sba.jpg
    - images/sigou/sbb.jpg
    - images/quiz/Q001/A0010.png
    - images/quiz/Q001/A0011.png
    - images/quiz/Q001/A0012.png
    - images/quiz/Q001/Q001.png
    - images/quiz/Q002/Q002.png
    - images/quiz/Q002/A0020.png
    - images/quiz/Q003/Q003.png
    - images/quiz/Q003/A0030.png
    - images/quiz/Q003/A0031.png
    - images/quiz/Q004/Q004.png
    - images/quiz/Q004/A0040.png
    - images/quiz/Q004/A0041.png
    - images/quiz/Q005/Q005.png
    - images/quiz/Q005/A0050.png
    - images/quiz/Q005/A0051.png
    - images/quiz/Q005/A0052.png
    - images/quiz/Q006/Q006.png
    - images/quiz/Q006/A0060.png
    - images/quiz/Q006/A0061.png
    - images/quiz/Q006/A0062.png
    - images/quiz/Q007/Q007.png
    - images/quiz/Q007/A0070.png
    - images/quiz/Q007/A0071.png
    - images/quiz/Q007/A0072.png
    - images/juuniun/上流下流.jpg
    - images/juuniun/エレベータ階段.jpg
    - images/juuniun/大きい石小さい石.jpg
    - images/juuniun/自分の荷をあげる.jpg
    - images/juuniun/十二運の強弱.jpg
    - images/juuniun/十二運の読み.jpg
    - images/juuniun/十二運と一生1.jpg
    - images/juuniun/十二運と一生2.jpg
    - images/juuniun/十二運の出し方.jpg
    - images/juuniun/四旺.jpg
    - images/juuniun/四衰.jpg
    - images/juuniun/四旺と四衰.jpg
    - images/juuniun/宇多田ヒカル.jpg
    - images/juuniun/宇多田ヒカル十二運.jpg
    - images/juuniun/四旺四衰特徴.jpg


